#mongodb set up
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true

  #redis set up
  redis:
    host: localhost
    port: 6379

logging:
  level:
    web: DEBUG

server:
  error:
    include-stacktrace: never